---
# Source: stakater-push-main-tag-bitbucket/templates/task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-monorepo-package-helm-charts
  labels:
    app.kubernetes.io/version: "0.0.0"
spec:
  params:
    - name: GIT_EMAIL
      type: string
      default: "tekton@robot.com"
    - name: CUSTOM_CA_CERT_PATH
      type: string
      default: ""
    - name: REGISTRY
      type: string
    - name: HELM_REG_CREDS_SECRET_NAME
      description: Helm registry credentials secret name
      default: "helm-reg-creds"  
  steps:
    - args:
        - '-c'
        - >
          set -e

          PIPELINE_BOOKMARK_TAG="tekton-git-marker";
          ln -s /tekton/creds/.ssh /root/.ssh;
          git config --global --add safe.directory $(workspaces.source.path);

          if [[ "$(params.CUSTOM_CA_CERT_PATH)" != "" ]]; then
            git config http.sslCAInfo $(params.CUSTOM_CA_CERT_PATH)
          fi
          

          if [ $(git tag -l "$PIPELINE_BOOKMARK_TAG") ]; then

            git config user.email $(params.GIT_EMAIL);

          
            pwd;


            git diff HEAD..$PIPELINE_BOOKMARK_TAG --name-only -r | while read CHART;
            do
            
              echo $CHART;
              if [ $(basename "$CHART") == "Chart.yaml" ]; then

                CHART_NAME=$(cat $CHART | awk -F "name: " 'NF>1{print $2;exit; }')
                echo $CHART_NAME

                CHART_VERSION=$(cat $CHART | awk -F "version: " 'NF>1{print $2;exit; }')
                echo $CHART_VERSION

                CHART_TAG="$CHART_NAME-$CHART_VERSION"
                echo $CHART_TAG
                
                CHART_DIR=$(dirname $CHART)
                echo $CHART_DIR

                # check if git tag exists for chart. Should be {Chart.name-chart.version}
                if [ git rev-parse ${TAG} >/dev/null 2>&1 ]; then
                    echo "chart version $TAG already exist, wont push helmchart ";
                    continue
                fi

                CHART_PACKAGE=$(helm package --version $CHART_VERSION -u $CHART_DIR 2>&1)
                if [ $? -ne 0 ]; then
                    echo "Error occurred while packaging the Helm chart.";
                    echo $?;
                    echo $CHART_PACKAGE;
                    continue;
                fi

                CHART_PACKAGE=$(echo "$CHART_PACKAGE" | cut -d":" -f2 | tr -d '[:space:]')

                echo $CHART_PACKAGE

                if [ "$(params.CUSTOM_CA_CERT_PATH)" != "" ]; then
                    curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.REGISTRY) --upload-file "$CHART_PACKAGE" --cacert $(params.CUSTOM_CA_CERT_PATH)
                else
                    curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.REGISTRY) --upload-file "$CHART_PACKAGE" 
                fi

                git tag -am "Bump version to $CHART_TAG" $CHART_TAG;

              else
                echo "Chart.yaml not found in directory";
              fi

            done
          fi

          git push --tags;
      command:
        - /bin/bash
      env:
        - name: REG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.HELM_REG_CREDS_SECRET_NAME)
              key: password
              optional: true
        - name: REG_USER
          valueFrom:
            secretKeyRef:
              name: $(params.HELM_REG_CREDS_SECRET_NAME)  
              key: username
              optional: true
      image: 'stakater/pipeline-toolbox:v0.0.36'
      name: push-main-tag
      resources: {}
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
    - name: ssh-directory
      optional: true