---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-helm-package-and-upload-to-nexus
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[push]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/crikke/pac-demo/main/stakater-monorepo-package-helm-charts.yaml"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: ssh_repo_url
    - name: revision
    - name: registry
    - name: custom-ca-path
      optional: true
    - name: helm-creds-secret
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
        - name: ssh-directory
          workspace: ssh-directory
        - name: ssl-ca-directory
          workspace: ssl-ca-directory
      params:
        - name: url
          value: $(params.ssh_repo_url)
        - name: revision
          value: $(params.revision)
          workspace: source
        - name: depth
          # fetch all commits
          value: 10
    - name: helm-package-and-push-charts
      taskRef:
        name: stakater-monorepo-package-helm-charts
        kind: Task
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - fetch-repository
      params:
        - name: REGISTRY
          value: $(params.registry)
        - name: CUSTOM_CA_CERT_PATH
          value: $(params.custom-ca-path)
        - name: HELM_REG_CREDS_SECRET_NAME
          value: $(params.helm-creds-secret)
  workspaces:
    - name: ssl-ca-directory
    - name: ssh-directory
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
