---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pac-demo
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[push]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/crikke/pac-demo/main/stakater-monorepo-package-helm-charts.yaml"

    # # Use golangci-lint from the hub to test our Golang project
    # pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/stakater-tekton-catalog/create-git-tag/0.0.12/task/stakater-create-git-tag/stakater-create-git-tag.yaml"
    # # pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/stakater-tekton-catalog/helm-push/0.0.15/task/stakater-helm-push/stakater-helm-push.yaml"
    # pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/stakater-tekton-catalog/helm-push/feature/debug/task/stakater-helm-push/stakater-helm-push.yaml"
    # pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/stakater-tekton-catalog/push-main-tag-bitbucket/feature/do-not-use-x-auth/task/stakater-push-main-tag-bitbucket/stakater-push-main-tag-bitbucket.yaml"

    # You can add more tasks by increasing the suffix number, you can specify
    # them as array to have multiple of them.
    # browse the tasks you want to include from hub on https://hub.tekton.dev/
    #

    # how many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: repo_url
    - name: revision
    - name: registry
    - name: helm-creds-secret
    - name: custom-ca-path
      optional: true
    - name: git-auth-secret
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
        - name: ssl-ca-directory
          workspace: ssl-ca-directory
          optional: true
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
          workspace: source
    - name: helm-package-and-push-charts
      taskRef:
        name: stakater-monorepo-package-helm-charts
        kind: Task
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo_url)
        - name: GIT_REVISION
          value: $(params.revision)
          workspace: source
        - name: BITBUCKET_TOKEN
          value: $(params.git-auth-secret)
        - name: REPO_URL
          value: $(params.repo_url)
        - name: REGISTRY
          value: $(params.registry)
        - name: CUSTOM_CA_CERT_PAT
          value: $(params.custom-ca-path)

    # - name: stakater-create-git-tag
    #   runAfter:
    #     - fetch-repository
    #   taskRef:
    #       name: stakater-create-git-tag
    #       kind: Task
    #   params:
    #     - name: PR_NUMBER
    #       value: "NA"
    #     - name: GIT_REVISION
    #       value: $(params.revision)
    #   workspaces:
    #     - name: source
    #       workspace: source
    #     - name: ssh-directory
    #       workspace: ssh-directory
    # - name: stakater-helm-push
    #   taskRef:
    #     name: stakater-helm-push
    #     kind: Task
    #   runAfter:
    #   - stakater-create-git-tag
    #   workspaces:
    #     - name: source
    #       workspace: source
    #   params:
    #       - name: REGISTRY
    #         value: $(params.registry)
    #       - name: HELM_REG_CREDS_SECRET_NAME
    #         value: $(params.helm-creds-secret)
    #       - name: CHART_PATH
    #         value: $(params.chart-path)
    #       - name: CUSTOM_CA_PATH
    #         value: $(params.custom-ca-path)
    #       - name: SEM_VER
    #         value: $(tasks.stakater-create-git-tag.results.GIT_TAG)
    # - name: stakater-push-main-tag-bitbucket
    #   taskRef:
    #     name: stakater-push-main-tag-bitbucket
    #     kind: Task
    #   runAfter:
    #   - stakater-helm-push
    #   params:
    #     - name: GIT_REVISION
    #       value: $(params.revision)
    #     - name: REPO_URL
    #       value: $(params.repo_url)
    #     - name: SEM_VER
    #       value: $(tasks.stakater-create-git-tag.results.GIT_TAG)
    #     - name: CUSTOM_CA_CERT_PATH
    #       value: $(params.custom-ca-path)
    #     - name: BITBUCKET_TOKEN
    #       value: $(params.git-auth-secret)
    #   workspaces:
    #     - name: source
    #       workspace: source
  workspaces:
    - name: basic-auth
      optional: true
    - name: ssl-ca-directory
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
