---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-helm-package-and-upload-to-nexus
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: repo_url
    - name: revision
    - name: registry
    - name: custom-ca-path
      optional: true
    - name: helm-creds-secret
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
        - name: ssl-ca-directory
          workspace: ssl-ca-directory
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
          workspace: source
        - name: depth
          # fetch all commits
          value: 0
    - name: helm-package-and-push-charts
      taskRef:
        name: stakater-monorepo-package-helm-charts
        kind: Task
      workspaces:
        - name: source
          workspace: source
        - name: basic-auth
          workspace: basic-auth
      runAfter:
        - fetch-repository
      params:
        - name: REGISTRY
          value: $(params.registry)
        - name: CUSTOM_CA_CERT_PATH
          value: $(params.custom-ca-path)
        - name: HELM_REG_CREDS_SECRET_NAME
          value: $(params.helm-creds-secret)
        - name: revision
          value: $(params.revision)
  workspaces:
    - name: ssl-ca-directory
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
